### ISSUE TITLE
dbus: stopping now requires an optional argument profile_switch

### ISSUE THREAD

**Issue by jelly** [redhat-performance/tuned#551]
Since https://github.com/redhat-performance/tuned/commit/7f3a79bbd6e1152d15187d5b071b64af08706bf4#diff-f86334dc9215b06e3455f0dd706ce4979971f12d39c11587078c6010dba4ff7fR120 it is no longer possible to call stop without a `profile_switch` argument.

Previously:
```
[root@fedora-38-127-0-0-2-2201 ~]# busctl call com.redhat.tuned /Tuned com.redhat.tuned.control stop
b true
```

Since the last RC
```
[root@fedora-rawhide-127-0-0-2-2201 ~]# busctl call com.redhat.tuned /Tuned com.redhat.tuned.control stop
Call failed: TypeError: stop() missing 1 required positional argument: 'profile_switch'
```

I'm wondering if this API change is intentional, or if it should be an optional argument.

BTW, it seems to me that the introspection is wrong now?

```
.start                         method    -         b            -
.stop                          method    v         b            -
```

```
[root@fedora-rawhide-127-0-0-2-2201 ~]# busctl call com.redhat.tuned /Tuned com.redhat.tuned.control stop b false
Call failed: TypeError: stop() got multiple values for argument 'caller'
```

**Comment by yarda** [comment]
Thanks, good catch, it was introduced by 7f3a79bbd6e1152d15187d5b071b64af08706bf4.

**Comment by yarda** [comment]
@RHEmployee it would be great to have gating test for the API to prevent such problems in the future.

**Comment by RHEmployee** [comment]
@yarda Hi. Would you please describe what exactly do you want to to cover in test?
Should be test aimed only to this issue or should cover wide use?
I'm happy to create downstream test and upstream it.
